# Practice with NumPy

Author: Greg Wray  
2026-MAR-22 

In [2]:
import numpy as np
import sys
from datetime import date
import math
import random

## NumPy

**NumPy** is a library of data structures and functions for working arrays and matrices in Python. It is widely used in science and engineering. NumPy is a foundational library, not only used on its own, but required for many other libraries. 

NumPy provides a large set of functions and methods written in C that provide improved performance over base Python functions. They include a full set of math, logic, and statistics functions, as well as functions specific to working with arrays and linear algebra. 

Access the official NumPy documentation [here](https://numpy.org/doc/stable/index.html).

## Introducing ndarrays   

The fundamental data structure provided by NumPy is the **ndarray**, which stands for n-dimensional array. As the name implies, ndarrays can be created in any number of dimensions: vector (1-dimensional), array (2-dimensional), matrix (3-dimensional), tensor (4-dimensional), and so forth. 

In contrast to base Python iterables, ndarrays have a fixed size that is specified at creation.  

An ndarray holds a single data type; it can be any valid Python data type or object, although most commonly numeric and Boolean. While ndarrays can hold strings and even data structures, this is not their primary intended purpose.

Importantly, ndarrays are optimized for **speed** and for **vectorized** operations. 
   
To illustrate the **performance** difference, we can use `timeit`, a Jupyter "magic" that measures the time required execute a Python statement. Note that the ndarray is processed 1-2 orders of magnitude faster. Try some other operations for comparison. 

In [88]:
# create a big list and a big ndarray
my_list = list(range(1_000_000))
my_vec = np.arange(1_000_000)

In [17]:
# apply a function to each item and time the operation
%timeit result = [x * 2.333 for x in my_list]

In [18]:
# apply a function to each item and time the operation
%timeit result = my_vec * 2.333

To illustrate **vectorized** operations, we can create another array, then carry out arithmetic and matrix operations directly on the array object without needing to loop through each element. This also makes code *much* easier to understand. 

In [2]:
# create an array (syntax will be explained later)
my_arr = np.arange(0, 100, 5).reshape(4,5)
my_arr

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [13]:
# multiply an array by a scalar


In [14]:
# add arrays


In [15]:
# calculate the square root of every item in an array


In [16]:
# transpose an array


## Creating ndarrays

When working with tabular data, creating a data frame from scratch is uncommon. In contrast, it is often useful to create an array from scratch. NumPy provides a set of useful methods that allow you to quickly generate arrays and populate them with specified values and spatial patterns. The following examples illustrate the most common ways to generate ndarrays; refer to the NumPy documentation for other approaches.

**Create an ndarray from an existing iterable.** The general-purpose method for creating ndarrays is `np.array()`. You can pass any iterable to it, but lists are the most common. (With dictionaries, you first need to convert to a list or else it will treat the entire dictionary as a single element in the array.) Nested iterables are automatically interpreted as having the number of dimensions corresponding to the depth of nesting. 

In [57]:
# generate some lists
simple_list = [22, -1, 5, 17, 9, 24, 31, 99, -42]
nested_list = [[1, 8, 101, 50], [5, 1, 19, 44], [72, -4, 1, -30], [50, 37, -61, 1]]

In [58]:
# create a 1D ndarray from flat list


array([ 22,  -1,   5,  17,   9,  24,  31,  99, -42])

In [59]:
# check the data type


numpy.ndarray

In [97]:
# create a 2D ndarray from nested list


array([[  1,   8, 101,  50],
       [  5,   1,  19,  44],
       [ 72,  -4,   1, -30],
       [ 50,  37, -61,   1]])

**Create an ndarray filled with a specified value.** NumPy provides functions for creating specific kinds of arrays. The first argument in all cases is the *shape* of the array: pass the same number of integers as dimensions, with values corresponding to length of each dimension. For more than 1 dimension, pass a tuple.

In [19]:
# create a 1D ndarray filled with zeros


In [20]:
# create a 2D ndarray filled with zeros


In [21]:
# create a 3D ndarray filled with ones


In [22]:
# create an nD ndarray filled with a single value
# note the tuple containing the shape


In [23]:
# create a 2D array filled with random numbers


In [24]:
# create a 2D ndarray of 0s with 1s on the diagonal (identity matrix); .eye() is a synonym
# note: only needs 1 value, since an identify matrix is always a square


In [25]:
# create a 2D ndarray filled with a single number except with 1s on the diagonal
#   first create the identity arrray as above, then filter and reassign 0 values


**Create an ndarray by generating a sequence.** Use the `arange()` function to generate a sequence of numbers while creating an ndarray. This function is analogous to the `range()` function of base Python; however, instead of creating a range object, `arange()` directly creates a 1-dimensional ndarray. To convert this vector into a higher-dimensional object, simply append the `.reshape()` method and pass the shape: 2 integers for an array, 3 integers for a matrix, etc. Be sure to create an initial range that corresponds to the desired shape.

In [26]:
# generate a 1D ndarray from a sequence


In [27]:
# arange() takes the same optional arguments as range()


In [28]:
# use .reshape() to make a 2D ndarray; pass 3 numbers for a 3D ndarray


## Data types

NumPy provides a much larger set of atomic data types than base Python. Available data types are essentially the ones available in C, since much of NumPy is written in C. For numerics, you have control over not only integer, float, and complex types, but also amount of memory per item and whether you need negative values. In general, chose the smallest and simplest data type that can hold your data; this can result in signifcant savings in memory and compute time.   

Examples of NumPy data types are: `float64` (64-bit float), `uint8` (unsigned 8-bit integer), and `int32` (signed 32-bit integer). To use these data types, prefix with `np.`. You can also use generic names `int` and `float` if you are not concerned with memory and performance. Strings are a special case and won't be covered here. See the NumPy documentation for a full list of available data types and their names. 

**Specify data type at creation.** Use the optional `dtype` argument with most ndarray generator functions to indicate the data type you would like.   

In [29]:
# generate a 2D ndarray of small unsigned integers


In [30]:
# generate a 2D ndarray of medium floats


In [31]:
# generate a 2D ndarray of booleans; the easiest way is using full()


**Convert between data types.** Use the `.astype()` method to convert an existing ndarray to a different data type. You can check on the data type of an existing array by calling the `.dtype` attribute. The one exception is converting to Boolean: instead call `bool`.

In [32]:
# check data type
my_arr = np.identity(8)


In [33]:
# convert data type


In [34]:
# convert to Boolean; False = 0, True = any other value


## Input / output with arrays

While NumPy arrays can be extremely useful, there are many circumstances where you may need to move data into or out of this data structure. For instance, you may want to store the results of a simulation. The following examples illustrate some ways to move values into and out of ndarrrays. 

In [35]:
# return a standard Python list with nesting corresponding to array dimensions
#    See "Create an ndarray from an existing iterable" (above) for the opposite operation
my_arr = np.arange(10).reshape(2, 5)


In [36]:
# read from a .csv file directly into an ndarray


In [37]:
# save an ndarray as a .csv file
my_arr = np.arange(0, 20, dtype=np.int32).reshape(4, 5)


## Retrieving information about an ndarray

**Attributes.** NumPy provides several attributes and functions to retrieve information about an ndarray. The following are some of the more useful ones; consult the NumPy documentation for a full list and more information. These attributes and functions are particularly useful when you will be changing the size, shape, or dimensions of an array within a program. Some kinds of information can be returned from either a function or an attribute, because attributes can be chained while functions are more useful for functional programming. Remember that attributes should not be followed by `()`.

In [5]:
# create an array to work with
my_arr = np.arange(0, 400, 5).reshape(4, 4, 5)
print(my_arr)

[[[  0   5  10  15  20]
  [ 25  30  35  40  45]
  [ 50  55  60  65  70]
  [ 75  80  85  90  95]]

 [[100 105 110 115 120]
  [125 130 135 140 145]
  [150 155 160 165 170]
  [175 180 185 190 195]]

 [[200 205 210 215 220]
  [225 230 235 240 245]
  [250 255 260 265 270]
  [275 280 285 290 295]]

 [[300 305 310 315 320]
  [325 330 335 340 345]
  [350 355 360 365 370]
  [375 380 385 390 395]]]


In [38]:
# retrieve data type


In [39]:
# retrieve the number of dimensions; attribute


In [40]:
# retrieve the length of each axis; attribute


In [41]:
# retrieve the total number of elements; attribute


In [42]:
# retrieve the amount of memory that the array occupies; attribute


In [43]:
# retrieve the number of dimensions; function


In [44]:
# retrieve the number of dimensions; function


In [45]:
# retrieve the total number of elements; function


In [46]:
# retrieve the number of elements on axis 2; function


**Contents by condition.** To find out if an array contains values that meet a given condition, use the NumPy versions of `any()` and `all()`. These can be applied to a single axis with an optional argument; in this case, NumPy returns a list of values for each column or row (depending on which axis is requested). Note that compound conditions use `&` and `|` for AND and OR; to negate use `~`.

In [127]:
# first, create an array to use
my_arr = np.arange(0, 100, 5).reshape(4,5)
print(my_arr)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [47]:
# test whether any values in the array are larger than 50


In [48]:
# test whether all values in the array are positive


In [49]:
# test whether all values in each column are larger than 10


In [50]:
# test whether any values in the array meet a compound condition


## Indexing ndarrays
Use square bracket indexing to access values in ndarrays. This works similarly to plain Python: indexing is zero-based and accepts negative values as well as slices, including open slices. You can pass up to the same number of arguments as array dimensions; fewer arguments than dimensions will retrieve sub-arrays (see examples below). Arguments are separated by commas; each argument can have 1, 2, or 3 values separated by colons (start; start:stop; and start:stop:step).   

When mentally mapping indexes onto an ndarray, a good rule of thumb is to work your way from outer to inner representation. In a 2-dimensional array, the outer dimension (axis = 0, first argument) refers to rows and the inner dimension (axis = 1, second argument) refers to columns. In a 3-dimensional array, the outer dimension (axis = 0) refers to "planes", the intermediate (axis = 1) refers to rows, and the inner (axis = 2) refers to columns. Another way to think about this is that internal columns are always the last dimension, and internal rows are always the second-to-last. If you require 4- and higher dimensional arrays (tensors), the same basic principles hold, but are beyond the scope of this notebook.

In [21]:
# create 1-dimensional array
my_vec = np.arange(10)
print(my_vec)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
# index a 1-dimensional array


In [23]:
# create 2-dimensional array
my_arr = np.arange(36).reshape(6, 6)
print(my_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [52]:
# index a 2-dimensional array; the first value refers to rows, the second to columns


In [25]:
# create a 3-dimensional array
my_matrix = np.arange(0, 400, 5).reshape(4,4,5)
print(my_matrix)

[[[  0   5  10  15  20]
  [ 25  30  35  40  45]
  [ 50  55  60  65  70]
  [ 75  80  85  90  95]]

 [[100 105 110 115 120]
  [125 130 135 140 145]
  [150 155 160 165 170]
  [175 180 185 190 195]]

 [[200 205 210 215 220]
  [225 230 235 240 245]
  [250 255 260 265 270]
  [275 280 285 290 295]]

 [[300 305 310 315 320]
  [325 330 335 340 345]
  [350 355 360 365 370]
  [375 380 385 390 395]]]


In [53]:
# index a 3-dimensional array
#    the first value refers to the separated layers, the second to rows, and the third to columns


**Subsetting in multiple dimensions.** Indexing a multidimensional array with the *same number of indices as dimensions* returns a single element. For instance, `my_arr[3,2,1]` returns the value of a single element if `my_arr` has 3 dimensions. To retrieve a single element from a 2-dimensional array requires 2 indices. And so forth.

Indexing a multidimensional array with *fewer indices than dimensions* returns a subdimensional array. For instance, `my_arr[2,1]` returns a 2-dimensional array if `my_arr` has three dimensions. And so forth.

In [140]:
# create a 3-dimensional array to work with
my_matrix = np.arange(0, 400, 5).reshape(4,4,5)
print(my_matrix)

[[[  0   5  10  15  20]
  [ 25  30  35  40  45]
  [ 50  55  60  65  70]
  [ 75  80  85  90  95]]

 [[100 105 110 115 120]
  [125 130 135 140 145]
  [150 155 160 165 170]
  [175 180 185 190 195]]

 [[200 205 210 215 220]
  [225 230 235 240 245]
  [250 255 260 265 270]
  [275 280 285 290 295]]

 [[300 305 310 315 320]
  [325 330 335 340 345]
  [350 355 360 365 370]
  [375 380 385 390 395]]]


In [54]:
# retrieve a single element from a 3-dimensional array


In [55]:
# retrieve a 1-dimensional vector (row) from a 3-dimensional array
# (retrieving a single column requires slicing; see next section)


In [56]:
# retrieve a 2-dimensional array from a 3-dimensional array


**Indexing with slices.** Slices provide a powerful and elegant way to access multiple values within arrays. Getting comfortable with slicing will let you efficiently index rows and columns of 2-dimensional arrays, and planes, rows, and columns in any dimension of 3-dimensional arrays. Practice indexing with slices on 1- and 2- dimensional arrays first, as it quickly gets complicated with 3- and higher-dimensional arrays. With a 2-dimensional array, the first argument refers to rows and second to columns.

In [73]:
# create a 2-dimensional array to work with
my_arr = np.arange(36).reshape(6, 6)
print(my_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [57]:
# retrieve the first column (axis 1)


In [58]:
# retrieve the fourth row (axis 0)


In [59]:
# retrieve a smaller 2-dimensional array


In [60]:
# negative indices are useful for retrieving the highest-index values


In [61]:
# retrieve even-numbered columns 


In [62]:
# retrieve an array with the order of rows, but not columns, reversed


When indexing a 3-dimensional array, work your way from the outermost to innnermost brackets.

In [80]:
# create an array to work with
my_matrix = np.arange(0, 400, 5).reshape(4,4,5)
print(my_matrix)

[[[  0   5  10  15  20]
  [ 25  30  35  40  45]
  [ 50  55  60  65  70]
  [ 75  80  85  90  95]]

 [[100 105 110 115 120]
  [125 130 135 140 145]
  [150 155 160 165 170]
  [175 180 185 190 195]]

 [[200 205 210 215 220]
  [225 230 235 240 245]
  [250 255 260 265 270]
  [275 280 285 290 295]]

 [[300 305 310 315 320]
  [325 330 335 340 345]
  [350 355 360 365 370]
  [375 380 385 390 395]]]


In [63]:
# retrieve the value of a column from the third dimension of a 3-dimensional array


In [64]:
# retrieve the value of a row from the second dimension of a 3-dimensional array


**Fancy indexing.** It is also possible to index an ndarray using a list of integers. NumPy calls this *fancy indexing*. This approach is useful when you want to extract discontinuous or out-of-order items, rows, or columms. Unlike regular square bracket indexing, which returns a *view* of the original, fancy indexing always returns a *new data object*. The examples below use 2-dimensional arrays, but fancy indexing works with any number of dimensions (if you can wrap your head around how to do it). Note that indexing in the nested array is by a list of values in dimension zero, followed by a list of values in dimension 1; do not pass separate pairs of values for each item you want back. Fancy indexing returns another nparray object.

In [156]:
# create an array to work with
my_arr = np.arange(32).reshape((8, 4))
print(my_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [65]:
# retrieve a discontinuous set of individual items using fancy indexing
#   note that we are passing a nested list; the two sub-lists must be the same length


In [66]:
# retrieve a discontinuous set of rows using fancy indexing
#   note that we are passing a list to square bracket indexing


In [67]:
# retrieve a discontinuous set of columns using fancy indexing
#   note that we are passing a list to the second argument of square bracket indexing
#   note that we need to pass :, before the list to indicate that the list applies to axis=1


**Boolean indexing.** Recall that Boolean indexing involves first making a "mask": a data object that containts True/False values for each item in the object you want to filter. Any valid condition can be used to make the mask. Boolean indexing is particularly useful when you want to perform the same filtering step more than once. Like fancy indexing, Boolean indexing with ndarrays always returns a new object. 

In [8]:
# create an array
simple_list = [21, -1, 5, 65, 17, 9, 24, 31, 99, -44, 13, -4, 29, 82, 36]
my_arr = np.array(simple_list).reshape(5, 3)
print(my_arr)

[[ 21  -1   5]
 [ 65  17   9]
 [ 24  31  99]
 [-44  13  -4]
 [ 29  82  36]]


In [68]:
# create a mask based on whether values are is divisible by 3


In [69]:
# same, but just for the first column


In [70]:
# alternatively, create a mask using where()


In [71]:
# apply the mask: retrieve values in second and third columns 
# based on True/False values in first column


## Subsetting and copying ndarrays
**Views and copies.** When assigning subsets of ndarrays, values are typically *not* copied unless specifically requested. This saves memory and compute time. However, you need to be aware that modifications to a slice or subset will update the source array. Use the `copy()` function if you want to create a distinct object in memory. Fancy indexing and Boolean indexing are exceptions: they always create a copy by default. NumPy documentation distinguishes between *views* and *copies* to make it clear which kind of behavior to expect.

In [72]:
# updating a view updates the source array
my_arr = np.arange(0, 6)		


In [73]:
#  updating a copy of a view does not update the source array
my_arr = np.arange(0, 6)		


**Subsetting by condition.** You can retrive values meeting any valid logical expression. Note that filtering returns a 1-dimenstional array, regardless of the number of dimensions in the input array. 

In [3]:
# first, create an array
my_arr = np.random.rand(6, 4)
print(my_arr)

[[0.8436234  0.9852591  0.37082626 0.55435102]
 [0.39916242 0.05528852 0.61263776 0.29908783]
 [0.11804724 0.35271173 0.72654599 0.57006606]
 [0.5131893  0.59575485 0.60197837 0.7530835 ]
 [0.96001347 0.84064068 0.86991913 0.71794024]
 [0.91788622 0.30887011 0.65426413 0.77170745]]


In [74]:
# filter for values greater than or equal to 0.75


If you want the indices rather than the values, use `where()`. This will return one ndarray of indexes for each dimension of the ndarray you pass to the function. If there is more than one dimension, the returned arrays are wrapped in a tuple. For example, applying `where()` to a 2-dimensional array will return a tuple containing two ndarrays: the first with values in axis 0 and the second with values in axis 1. Pair the first value in the first array with the first value in the second array to get the coordinates of the first item, and so forth.

In [75]:
# filter for indexes of values greater than or equal to 0.75


## Updating subsets of an ndarray.

In all of the examples below, the original ndarray is updated in-place. 

**Update with a single value.** To update a subset of items, provide an index and a new value. This works for single items or slices. To update all items, use the `.fill()` method.

In [168]:
# create an array to work with
my_arr = np.zeros((4, 5), dtype=int)
print(my_arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [76]:
# replace a single value in a 2-dimensional array


In [77]:
# replace a 2-dimensional slice of values in a 2-dimensional array with a scalar


In [78]:
# replace all values in an ndarray with a single new value


**Update from an iterable.** You can update values in all or a specified subset of items an ndarry using `copyto()` and providing an iterable containing the new values. The examples below update from a flat list, but you can use  nested iterables to update in more than 1 dimension. Make sure the size and dimensions of the indexing and iterable are the same!

In [38]:
# create an array to work with
my_arr = np.zeros((4, 5), dtype=int)
print(my_arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [35]:
# create values to use for updating; lists and tuples both work
new_row = [-1, -2, -3, -4, -5]          
new_col = (-10, -20, -30, -40)
new_area = [[222, 333], [444, 555]]

In [79]:
# replace values in second row 


In [80]:
# replace values in third column 


In [81]:
# replace a 2-dimensional slice from a nested iterable


**Update based on condition.** Use any logical expression and supply a new value. Use `&` and `|` as operators to create compound conditions (note: differen from base Python, which uses `and` and `or`). Use `~` to negate any expression or sub-expression.

In [8]:
# create an array to work with
my_arr = np.arange(0, 100, 5).reshape(4,5)
print(my_arr)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [83]:
# replace all values divisble by 3 with 999


In [82]:
# replace all values divisble by 3 and less than 50 with 999


## Math and functions with ndarrays

The standard arithmetic and logical operators can be applied to ndarrays for vectorized (implicit looping) operations. Numpy also provides a large number of functions optimized to work with ndarrays called "universal functions" or "ufuncs" for short. They provide vectorized operations, avoiding the need for loops. Ufuncs are written in C and are often much faster than applying standard Python functions. Some examples are shown below. See the NumPy documentation for a full list of ufuncs. When working with ndarrays, be sure to specify the `np.` version, as the names are often identical to standard Python functions.

In [42]:
# create 2 arrays to work with
arr_A = np.arange(1, 101, 5).reshape(4,5)
arr_B = np.arange(1, 61, 3).reshape(4,5)
print(arr_A, '\n')
print(arr_B)

[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]] 

[[ 1  4  7 10 13]
 [16 19 22 25 28]
 [31 34 37 40 43]
 [46 49 52 55 58]]


In [84]:
# return the product of every item multiplied by a constant


In [85]:
# return the square root of every item; using the NumPy version!


In [86]:
# return boolean values by applying a condition to every item


In [87]:
# return the sum of two arrays


In [88]:
# there are trig and log ufunctions 


In [89]:
# return boolean values based on a condition comparing two arrays


In [90]:
# return boolean values based on a condition comparing two arrays


**Math updates in-place.** For simple arithmetic, you can use any of the augmentated assignment operators.

In [91]:
# Multiply all values by 3 in-place 


In [92]:
# Divide all values by 3 in-place


## Summary statistics
Many of the summary statistics below can be called as functions or methods using the same name. Many can be applied to the entire array or just one dimension of a multi-dimensional array.

In [20]:
# first, create an array to work with
nested_list = [[1, 8, 101, 50], [5, 1, 19, 44], [72, -4, 1, -30], [50, 37, -61, 1]]
my_arr = np.array(nested_list)
print(my_arr)

[[  1   8 101  50]
 [  5   1  19  44]
 [ 72  -4   1 -30]
 [ 50  37 -61   1]]


In [93]:
# return the mean value from an ndarray using a function


In [94]:
# return the mean value from an ndarray using a method


In [95]:
# return the sum of all items in an ndarray


In [96]:
# return the sums of rows


In [97]:
# return the largest value in an array


In [98]:
# return the largest value in each row


In [99]:
# return the variance of an array


In [100]:
# return the standard deviation of columns


## Sorting

NumPy provides a lot flexibility in sorting procedures and options. The following examples cover the basics, but you can control sorting in more granular ways if needed.

In [36]:
# first, create an array to work with
nested_list = [[1, 8, 101, 50], [5, 1, 19, 44], [72, -4, 1, -30], [50, 37, -61, 1]]
my_arr = np.array(nested_list)
print(my_arr)

[[  1   8 101  50]
 [  5   1  19  44]
 [ 72  -4   1 -30]
 [ 50  37 -61   1]]


In [101]:
# sort an array along a single axis; modifies the array in-place
#    default is to sort along the last axis (1 for a 2-dimensional array)


In [102]:
# sort an array along the first axis; modifies the array in-place


In [103]:
# to make a copy and preserve the original, use the function rather than the method


In [106]:
# the original is unmodified


In [104]:
# return items sorted across the entire array (flattens into a 1-dimensional array)


In [105]:
# return a sorted list of unique values


## Matrix operations

NumPy provides a rich set of functions and methods for matrix manipulations and linear algebra. The examples below illustrate some of the most common operations, but there are many more. 

**Reorganizing arrays.** Reorganizing involves changing the shape or dimensions of an array, or stacking (merging) two arrays. When stacking arrays, the joining edges must be of equal length. Any change to the dimensions or size of an array requires creating a new array, so assign output to save the result. A corollary is that none of these operations affect the original array(s).

In [60]:
# first, create an array to work with
nested_list = [[1, 8, 101, 50], [72, -4, 1, -30], [50, 37, -61, 1]]
my_arr = np.array(nested_list)
print(my_arr)

[[  1   8 101  50]
 [ 72  -4   1 -30]
 [ 50  37 -61   1]]


In [107]:
# returned a reshaped array
#    note that the number of items must match the new dimensions


In [108]:
# return the transpose of the array


In [109]:
# synonym for getting the transpose of the array


In [110]:
# return a flattened version of the array in 1 dimension
#    follows row order


In [111]:
# vertically stack arrays
arr_V1 = np.array([1, 2, 3, 4])
arr_V2 = np.array([5, 6, 7, 8])


In [112]:
# horizontally stack arrays
arr_H1 = np.ones((2, 4))
arr_H2 = np.zeros((2, 2))


**Matrix multiplication.** 

In [51]:
# construct 2 matrices to multiply
arr_1 = np.ones((2,3))
arr_2 = np.full((3,2), 4)
print(arr_1, '\n')
print(arr_2)

[[1. 1. 1.]
 [1. 1. 1.]] 

[[4 4]
 [4 4]
 [4 4]]


In [113]:
# do matrix multiplication


**Determinant of a matrix.**

In [114]:
# find the derminant
my_arr = np.random.rand(6, 6)
print(my_arr)


[[0.65943224 0.48536805 0.64380718 0.97734819 0.40027303 0.46662188]
 [0.4778468  0.90322731 0.25194331 0.65331544 0.00793957 0.23669291]
 [0.76049825 0.3636206  0.38816775 0.01431622 0.19808734 0.87122077]
 [0.66862921 0.04855904 0.33190789 0.78535888 0.15429078 0.94231379]
 [0.15187625 0.1042773  0.29707145 0.41315018 0.48408522 0.39121067]
 [0.17829298 0.83808414 0.90868612 0.3778783  0.70926769 0.8721576 ]]


In [115]:
# sanity check: the identity matrix has a determiant of 1 regardless of matrix size
arr_i = np.identity(7)
print(arr_i)


[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
